set :domain, 'toto.tenders.exposed'
set :deploy_to, '/srv/elvis/staging/backend'
set :repository, 'https://github.com/tenders-exposed/elvis-backend.git'
set :branch, 'master'
set :user, 'elvis'
set :rails_env, 'staging'
